version: '3'

services:
  restaurant_review_service:
    build: ./restaurant_review_service
    container_name: restaurant_review_service
    ports:
      - "8000:8080"
  
  review_predictions_service:
    build: ./review_predictions_service
    container_name: review_predictions_service
    ports:
      - "8001:8081"
  