version: '3'

services:
  restarurant_review_service:
    build: ./restaurant_review_service
    ports:
      - "8000:8080"
  
  review_predictions_service:
    build: ./review_predictions_service
    ports:
      - "8001:8080"
  